config/routes.rb
Rails.application.routes.draw do
 resources :articles
root 'pages#index'
   get 'about', to: 'pages#about'
   get 'signup', to: 'users#new'
   resources :users, except: [:new]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title,:user_id, :description, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :articles
 validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
 validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }
 has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	protect_from_forgery with: :exception
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in to perform that action"
			redirect_to root_path
		end
	end
	
	def check_user_is_logged_in?
		if !current_user
			redirect_to root_path
		else
			puts "#{current_user.username} is logged in"
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:edit,:update,:show,:destroy]
  before_action :check_user_is_logged_in?, only: [:new, :create]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = User.find(session[:user_id]).id
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  def show
  end	

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated"
      redirect_to article_path(@article)
    else
      flash[:notice] = "Article was not updated"
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash.now[:success] = "Deleted Successfully."
    redirect_to articles_path
  end

  private 
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
   @article = Article.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create 
		user = User.find_by(email: params[:session][:email].downcase)
		if user  && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have logged in"
			redirect_to users_path(user)
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
	@user = User.new
end
def create
	@user = User.new(user_params)
  if @user.save
   flash[:success] = "Welcome to the alpha blog #{@user.username}"
   redirect_to articles_path
  else
   render 'new'
  end
end
def edit
  @user = User.find(params[:id])
 end
 def update
  @user = User.find(params[:id])
  if @user.update(user_params)
   flash[:success] = "Your account was updated successfully"
   redirect_to articles_path
  else
   render 'edit'
  end
 end
 def show
  @user = User.find(params[:id])
  @user_articles = @user.articles
 end
 def index
  @users = User.all
end
private
def user_params
  params.require(:user).permit(:username, :email, :password)
end
end

app/views/articles/_form.html.erb
<%= render 'shared/flash' %>
<%= render 'shared/errors' %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
    <%= link_to 'Back', articles_path ,class: "btn btn-primary btn-success"%>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<%= render 'shared/article',haider:@articles %>
<div align="center">
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <% if @article.user %>
 <ul class="listing">
  <div class="row" align="center">
   <div class="col-md-4 col-md-offset-4">
    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
    <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
   </div>
  </div>
 </ul> 
 <% end %>
 <h4 class="center description"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@article.description) %>
 <div class="article-actions">
 <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
 <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
 <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
 </div>
</div>