config/routes.rb
Rails.application.routes.draw do
 resources :articles
root 'pages#index'
   get 'about', to: 'pages#about'
   get 'signup', to: 'users#new'
   resources :users, except: [:new]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title,:user_id, :description, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :articles
 validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
 validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }
 has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	protect_from_forgery with: :exception
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in to perform that action"
			redirect_to root_path
		end
	end
	
	def check_user_is_logged_in?
		if !current_user
			redirect_to root_path
		else
			puts "#{current_user.username} is logged in"
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:edit,:update,:show,:destroy]
  before_action :check_user_is_logged_in?, only: [:new, :create]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = User.find(session[:user_id]).id
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  def show
  end	

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated"
      redirect_to article_path(@article)
    else
      flash[:notice] = "Article was not updated"
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash.now[:success] = "Deleted Successfully."
    redirect_to articles_path
  end

  private 
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
   @article = Article.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create 
		user = User.find_by(email: params[:session][:email].downcase)
		if user  && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have logged in"
			redirect_to users_path(user)
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
	@user = User.new
end
def create
	@user = User.new(user_params)
  if @user.save
   flash[:success] = "Welcome to the alpha blog #{@user.username}"
   redirect_to articles_path
  else
   render 'new'
  end
end
def edit
  @user = User.find(params[:id])
 end
 def update
  @user = User.find(params[:id])
  if @user.update(user_params)
   flash[:success] = "Your account was updated successfully"
   redirect_to articles_path
  else
   render 'edit'
  end
 end
 def show
  @user = User.find(params[:id])
  @user_articles = @user.articles
 end
 def index
  @users = User.all
end
private
def user_params
  params.require(:user).permit(:username, :email, :password)
end
end

app/views/shared/_article.html.erb
<% haider.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
          <small>Created by: <%= article.user.username if article.user %>,
                    <%= time_ago_in_words(article.created_at) %> ago,
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <div class="article-actions">
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@article.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @article.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_flash.html.erb
 <% flash.each do |name, msg| %>
    <ul>
     <li><%= msg %></li>
    </ul>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Owner's", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Create Article", new_article_path %></li>

        <li><%= link_to "Users", users_path %></li>

        <li><%= link_to "Create user", signup_path %></li>
        <% if !current_user  %>
          <li><%= link_to "Login User", login_path %></li>
        <% else %>
          <li><%= link_to "Logout User", logout_path, :method => :delete  %>
        <% end %>
          
        </li>
      </ul>
    </div>
  </div>
</nav>